export const PLATFORM: string[] = ["all", "pc", "browser"];

export const CATEGORY: string[] = [
  "mmorpg",
  "shooter",
  "strategy",
  "moba",
  "racing",
  "sports",
  "social",
  "sandbox",
  "open-world",
  "survival",
  "pvp",
  "pve",
  "pixel",
  "voxel",
  "zombie",
  "turn-based",
  "first-person",
  "third-person",
  "top-down",
  "tank",
  "space",
  "sailing",
  "side-scroller",
  "superhero",
  "permadeath",
  "card",
  "battle-royale",
  "mmo",
  "mmofps",
  "mmotps",
  "3d",
  "2d",
  "anime",
  "fantasy",
  "sci-fi",
  "fighting",
  "action-rpg",
  "action",
  "military",
  "martial-arts",
  "flight",
  "low-spec",
  "tower-defense",
  "horror",
  "mmorts",
];

export const SORT_BY: string[] = [
  "release-date",
  "popularity",
  "alphabetical",
  "relevance",
];

export const FRIENDS_LIST = [
  { img: "friend.png", stat: "online", inGame: true },
  { img: "friend1.png", stat: "online", inGame: true },
  { img: "friend2.png", stat: "online", inGame: false },
  { img: "friend3.png", stat: "offline", inGame: false },
  { img: "friend4.png", stat: "offline", inGame: false },
  { img: "friend5.png", stat: "offline", inGame: false },
];

export const CHAT_LIST = [
  { img: "friend.png", stat: "online", mess: 3 },
  { img: "friend1.png", stat: "offline", mess: 1 },
];
